### ISSUE TITLE
people in different houses showing up in same room

### ISSUE THREAD

**Issue by KoolAiddTV** [MacgyverNZ/Fivem_burglary#2]
if i lockpick one house and my friend lockpicks the other we both show up in the same house, any way to fix it?

**Comment by King-Soul** [comment]
Is there a fix for it?

**Comment by KoolAiddTV** [comment]
Yes I got it working to an extent. only the players in mine are instanced and it's a little buggy with players being able to shoot eachother so I used a safezone resource to eliminate that possibility. If you want what I've worked on just add me on discord KoolAiddTV#3799

**Comment by burqka** [comment]
Because they have the same teleports to the same interior. Just change interiors.
